### ISSUE TITLE
Follow up with PES re: potential normative privacy specs

### ISSUE THREAD

**Issue by jasonanovak** [w3cping/administrivia#2]
There was a follow up from the TPAC f2f to follow up with @SnyderP re: potential normative privacy specs and whether they fit into webappsec scope.  If not, work with WebAppSec on updating their scope.  If so, then maybe no problem.

**Comment by samuelweiler** [comment]
The overhead for creating a new WGs is modest enough that we don't need to get out in front of this.

Instead, we should start docs here in the Privacy IG (e.g. on private/incognito mode).  If they clearly need to be in a WG, we can create a new one (or update the WebAppSec scope, if appropriate) within a reasonable timeframe.
