### ISSUE TITLE
Document / establish policy for what counts as a PING issue

### ISSUE THREAD

**Issue by pes10k** [w3cping/administrivia#28]
re: https://github.com/w3c/resource-timing/issues/222

This issue is to create a public document for how other groups should understand a PING issue.  As evidenced by the above discussion, different members of PING understand it differently. 

To date the process has been:
- Someone performs the privacy review
- Discussion on a PING call
- Reviewer opens issue in the WG/spec's repo with the outcome of the review and PING discussion
- Link to the above issue from [PING's tracking issues repo](https://github.com/w3cping/tracking-issues)
- Have follow up PING discussion / corrections / changes of opinion / etc take place in the original issue (the one in the WG/spec's repo, not the PING tracking issue)

This issue is intended to:
- See if PING members would like to formalize whats been the de facto process so far
- If so, document the above process, or amend if needed
- If people / members think having a single "PING issue" is too authoritative (e.g. it suggests too much consensus or similar), would it be worth capturing PING votes / dissents / etc
- Decide / discuss / clarify if issues opened by PING members, as part of PING privacy reviews, should have some kind of official sign-off (vote?) before being linked into the PING repo

Will make sure this is added to the next PING call agenda (currently scheduled for March 5th)

**Comment by yoavweiss** [comment]
Friendly PING! :P

**Comment by pes10k** [comment]
Howdy @yoavweiss , we've just written this up that i hope will answer most of the above question (though maybe indirectly)

https://github.com/w3c/ping/blob/main/howto-conduct-a-privacy-review.md

We'll discuss this full issue and how / where to document this concern too, if the above document doesn't cover.  Thanks for the ping!
