### ISSUE TITLE
Figure out how to make Security & Privacy questionnaire versioned

### ISSUE THREAD

**Issue by jasonanovak** [w3cping/administrivia#3]
The security & privacy questionnaire currently is not versioned.  We should figure out how to version it so that folks can say they were answering the questionnaire from such and such date (and to track edits to questions they find confusing).

How do we do this given other W3C specs do this?

**Comment by plehegar** [comment]
It seems to me that using the [history of publications](https://www.w3.org/standards/history/security-privacy-questionnaire/) would be enough to address this issue. Do we need to do more here?
