### ISSUE TITLE
charter should limit scope to stated deliverables

### ISSUE THREAD

**Issue by npdoty** [w3cping/administrivia#35]
While the scope might be the general topic, it would be easier for reviewers if the WG had a specific set of deliverables (some committed, some with more open-ended topics) that it would take on for standardization. 

Re-charters could be used to add new deliverables, and every occasional re-charter would also be a time to update the potential deliverables based on what is currently undergoing review or exploration.

(this was feedback from Apple, W3C Team, maybe others)

**Comment by plehegar** [comment]
See also https://www.w3.org/Privacy/IG/summaries/PING-minutes-20230706

**Comment by plehegar** [comment]
> @plehegar does this change match the preferred way of limiting scope to listed deliverables? [6eed4dd](https://github.com/w3cping/administrivia/commit/6eed4dd53ed253c181a6d1fbadfef79f321e3c33)

Yes, it does.

> The extra sentence there is to provide some guidance for changes to the charter in future, but I don't know if that's strictly necessary (as the charter will be changed in those cases, and the group/AC can change it in any way they see fit).

Your proposed sentence requires the Group to go through the AC to add new deliverables, without limiting the scope of the group. It does have the advantage that the Group can start discussion within its scope and continue them while asking to add a new deliverable in parallel (in other words, you can talk about thew new work but the Group won't be allowed to publish in /TR until a new charter is approved.

Of course, there is always a grey zone as well as a a judgment call and that's ok. For example, if an existing deliverable get split in 2 separate specifications, we wouldn't require a new AC review unless the scope of the 2 deliverables goes beyond the original scope before the split.
