### ISSUE TITLE
confirm testing policy

### ISSUE THREAD

**Issue by npdoty** [w3cping/administrivia#39]
Likely align with the common template guidance, but should tests be required for every feature, or also for every change to a CR specification?

**Comment by npdoty** [comment]
Proposed resolution here: https://github.com/w3cping/administrivia/commit/d056f7ba4b095964240a5f571db5919bb2c4a0c5

**Comment by npdoty** [comment]
Nick to re-include testing policy sentence, note that this is intended to be about normative feature changes

**Comment by npdoty** [comment]
@plehegar please take a look

**Comment by plehegar** [comment]
LGTM.
