### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by tomhenderson** [w3cping/administrivia#48]
The [public version of the charter page](https://w3cping.github.io/administrivia/2023/charter.html) has several dead links that make it difficult to learn what the current status of this effort is.  Specifically, these pages return 404:

- [Join the Privacy Working Group](https://www.w3.org/groups/wg/privacy/join)
- See the [group status page](https://www.w3.org/groups/wg/privacy/charters)

**Comment by plehegar** [comment]
the wg was approved
