### ISSUE TITLE
TPAC 2024 meeting planning - call for agenda items

### ISSUE THREAD

**Issue by npdoty** [w3cping/administrivia#49]
The Privacy Interest Group or the Privacy Working Group has two sessions scheduled for TPAC 2024. This issue is a call for agenda items or feedback on the group agenda for the upcoming meeting.

**Comment by AramZS** [comment]
Hi @npdoty I'd like to put GPC on the Agenda for the Tuesday slot! I think we would like to talk through standing issues and open the floor for additional discussion if there is any. I know that there's additional attention on this due to developments in California law and glad to talk through any new feedback from user agent vendors who have greater attention on this as a result.

**Comment by npdoty** [comment]
Updates on guidance documents, including:
* Privacy & Security Questionnaire
* Mitigating Browser Fingerprinting
* Privacy Principles (maybe a briefer update giving the AC review etc on Statement)

**Comment by pes10k** [comment]
If we have time that isn't taken up by more urgent matters, I think it'd be useful to discuss the kinds of things PING has historically considered in and out of scope for privacy reviews. Depending on the time available, it could be something like a mix of my best judgement of the following:

- the process role of privacy reviews (i.e. who submits reviews, and what "force" do they have or not have, in current W3C process)
- what issues (in my best judgement) have generally been considered in and out of scope for reviews, and what issues are in the unclear middle ground

And then, opportunity for discussion about the above (where do folks disagree? What did i get wrong or omit? What would be good to change going forward, even if i accurately capture the past and present state of things)

(Im emphasizing "me" in the above, not bc Im intending to give some very me-specific point of view, but to emphasize that any best-effort-objective presentation of past-and-present-practice will unavoidably be my own POV)

**Comment by npdoty** [comment]
An update on Credentials, and joint work item

**Comment by npdoty** [comment]
# PING at TPAC 2024

Notes: https://cryptpad.w3ctag.org/code/#/2/code/edit/4ht9YHtVS9AB4UBlh-oPvHej/

Chat in #ping in Slack

## Monday, 23 September 2024
14:00–16:00 Pacific Daylight Time

### Introductions, Code of Conduct
### Guidance Documents
### Conducting a privacy review
### [Charter updates](https://github.com/w3c/strategy/issues/414#issuecomment-2363997345) (brief)

## Tuesday 24 September 2024
09:00–10:30 Pacific Daylight Time
### Global Privacy Control: an update
### Credentials: user/privacy considerations
### AOB

**Comment by npdoty** [comment]
https://docs.google.com/document/d/1qKADVLZd8wxep0NWxHVmMXoJipdKn4ACxcJbNBBLF7g/edit
